# fly.toml file generated for da-course22 on 2023-03-17T23:39:18-07:00

app = "da-course22"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sjc"
processes = []

[build]
  image = "svanderwilt/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dxehwfg8d"
  CloudinarySettings__ApiKey= "363354319594157"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
